# Generated by Django 4.2.9 on 2024-02-01 14:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='наименование')),
                ('location', models.CharField(max_length=256, verbose_name='местоположение')),
                ('action', models.CharField(max_length=256, verbose_name='действие')),
                ('is_good', models.BooleanField(default=False, verbose_name='приятная')),
                ('award', models.CharField(blank=True, max_length=256, null=True, verbose_name='вознаграждение')),
                ('is_public', models.BooleanField(default=False, verbose_name='публичная')),
                ('period', models.IntegerField(choices=[(1, 'раз в день'), (2, 'раз в 2 дня'), (3, 'раз в 3 дня'), (4, 'раз в 4 дня'), (5, 'раз в 5 дней'), (6, 'раз в 6 дней'), (7, 'раз в неделю')], default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='период')),
                ('time_to_complete', models.DurationField(default=datetime.timedelta(seconds=120), verbose_name='продолжительность')),
                ('time', models.TimeField(blank=True, default=datetime.time(19, 34, 16, 983947), null=True, verbose_name='время выполнения')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
                'ordering': ('title',),
            },
        ),
    ]
